### ISSUE TITLE
:mutex => Mutex.new is only safe among instances of the same job

### ISSUE THREAD

**Issue by jmettraux** [HouseTrip/rufus-runner#5]
Hello,

I don't think one can tell using :mutex => Mutex.new is "safe". You can easily schedule two jobs that access the same thread-unsafe structure and since their mutexes will be different, there'll be no exclusivity.

John

**Comment by mezis** [comment]
> I don't think one can tell using :mutex => Mutex.new is "safe"

I think the README deserves some clarification :)

The default is to use a mutex that is created at load time, thus (by default) any two jobs created without specifying anothe mutex will use this shared one.

But of course, if two jobs get scheduled with `Mutex.new` things may go horribly wrong:

```
scheduler.run(name:'foo', mutex: Mutex.new) { ... }
scheduler.run(name:'foo', mutex: Mutex.new) { ... }
```

may run without exclusion.

Is this what you meant? Or did understand you completely wrong?

**Comment by mezis** [comment]
> The default is to use a mutex that is created at load time

To clarify my own comment—[that mutex](https://github.com/HouseTrip/rufus-runner/blob/master/lib/rufus-runner/tracking_scheduler.rb#L150), which will be shared accross all jobs and job instances unless otherwise specified.

**Comment by jmettraux** [comment]
Hello,

you read me right.

But your change to the README is misleading (and ineffective). The "safe default" underneath is still:

https://github.com/HouseTrip/rufus-runner/blob/master/lib/rufus-runner/tracking_scheduler.rb#L148-L154

If one reads the current README, one is lead to think that rufus-runner provides that global mutex, but it does not.

My initial issue still stands:

> I don't think one can tell using :mutex => Mutex.new is "safe". You can easily schedule two jobs
> that access the same thread-unsafe structure and since their mutexes will be different, there'll be no exclusivity

I should say "you can easily schedule two _distinct_ jobs...", perhaps.

You should fix the readme and the code, enforcing a global mutex on all jobs by default. Or teach your users about threads and mutexes and how to set them through rufus-runner and stop claiming that rufus-runner is safer than rufus-scheduler.

Kind regards.

**Comment by mezis** [comment]
> stop claiming that rufus-runner is safer than rufus-scheduler

hi again @jmettraux, I'm sorry we gave that impression. Our intent was just to provide "safe defaults" for the casual Rails developer who, as you rightly point out, might not be very familiar with thread safety issues.

> one is lead to think that rufus-runner provides that global mutex, but it does not

Ok, I think either we still have a misunderstanding. I hope I didn't get the code wrong.
The way I (thought I) implemented it is that `Rufus::TrackingScheduler::DefaultOptions[:mutex]` is created when the class is loaded (which happens in the main thread, once, when you `require` the gem).

This means that unless the `:mutex` option is overriden when calling `#run`, the exact same mutex instance is reused, which is (again, correct me if I'm wrong), safe.

Actually, as is, even different instances of the scheduler running in the same process will share one lock—again, on purpose, as (beyond Rails) lots of Ruby code out there isn't thread safe.

To further mitigate thread safety issues, each job "work block" gets forked to a separate process by default (although not doing so is a configurable option).
This means (or, again, that was the intent) that the locking mechanism you've built into `rufus-scheduler` is leveraged to prevent jobs form running concurrently by default, and the forking to prevent the code inside jobs to bump into thread-safety issues.

I'll reopen and keep this open until you're reasonably satisfied we've addressed your concern.

**Comment by jmettraux** [comment]
Hello Julien,

please don't re-open, the initial readme (before your fix) led me to believe that the mutex was created at each schedule.

Sorry, for my shallow reading skills. I think your readme fix is appropriate.

Sorry again for the noise.

John

**Comment by mezis** [comment]
Phew, you had be very worried there.
Thanks for the useful feedback, and I'll happily take any suggestions to clarify things further :)
